# Generated by Django 5.0.7 on 2024-08-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_user_followers_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
